languageCode = 'en-us'
title = 'Cache Valley Communities'
theme = 'community'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[sitemap]
changeFreq = ""
filename = "sitemap.xml"
priority = -1

[params]
titleCutting = true
animateStyle = "animated zoomIn fast"
github = "https://github.com/CacheValleyCommunities/"

[pagination]
# Number of pages to show per page
pagesPerSection = 6
# Number of pages to show in pagination controls
paginatePath = "page"

[[params.navlinks]]
name = "about/"
url = "/organizations/cachevalleycommunities/"

[[params.navlinks]]
name = "posts/"
url = "posts/"

[[params.navlinks]]
name = "organizations/"
url = "organizations/"

[[params.navlinks]]
name = "contributors/"
url = "/page/contributors/"

[[params.navlinks]]
name = "Github/"
url = "https://github.com/CacheValleyCommunities/new-website"

[permalinks]
posts = "/posts/:slug"

# Mount all content directories at their standard locations
[[module.mounts]]
source = "content"
target = "content"

# Additional mount for the old posts URL pattern
[[module.mounts]]
source = "content/posts"
target = "content/p"
