languageCode = 'en-us'
title = 'Cache Valley Communities'
theme = 'community'

[sitemap]
changeFreq = ""
filename = "sitemap.xml"
priority = -1

[params]
titleCutting = true
animateStyle = "animated zoomIn fast"

[[params.navlinks]]
name = "about/"
url = "/organizations/cachevalleycommunities/"

[[params.navlinks]]
name = "posts/"
url = "posts/"

[[params.navlinks]]
name = "organizations/"
url = "organizations/"

[[params.navlinks]]
name = "Github"
url = "https://github.com/CacheValleyCommunities/new-website"

[permalinks]
posts = "/p/:slug"

[[module.mounts]]
source = "content/posts"
target = "content/posts"

[[module.mounts]]
source = "content/posts"
target = "content/p"
